### ISSUE TITLE
issue with hyper library

### ISSUE THREAD

**Issue by iainwatt** [genesluder/python-apns#5]
I have been using your lib without error for a few months until it recently stopped working. We are using Apex (for Lambda) and simply redeployed the function that included 'gobiko.apns' in our requirements.txt 

The error is;

` GoAway frame could not be sent: 'NoneType' object has no attribute 'sendall'`

and the traceback is;

```
local variable 'res' referenced before assignment: UnboundLocalError
Traceback (most recent call last):
File "/var/task/main.py", line 79, in handle
send_ios_push(params, developer_id, ios_devices, bundle_id)
File "/var/task/main.py", line 149, in send_ios_push
extra=formatted_params['extra']
File "/var/task/gobiko/apns/client.py", line 78, in send_bulk_message
return res
UnboundLocalError: local variable 'res' referenced before assignment
```

I think it may be failing to establish an SSL connection but not sure how to fix it. 

AWS Lambda runs on python 2.7.12.

**Comment by Proper-Job** [comment]
@iainwatt 
I haven't looked into your issue specifically. But since you're mentioning an SSL problem with regards to push notifications.  Are you by any chance deploying using gevent?  Because gevent monkey patches the SSLSocket implementation.  I've had problems with gevent and APNS in the past.

**Comment by iainwatt** [comment]
Thanks for looking into it, I am deploying using [Apex](http://apex.run/#structuring-projects). When you deploy Apex pulls in the  all the libs from requirements.txt so on each deployment it seemed to be continually replacing some of the libs required in you package. I will try again and only load your package to Lambda once.

**Comment by mark-anders** [comment]
I'm seeing this too. I'm attempting to send_message from a Flask app in development mode, so using the Flask cli, which I think doesn't use gevent.

**Comment by mvanbaak** [comment]
hyper is no longer maintained. They (hyper team) suggest switching to httpx.
I did so. See #32
